Refactor icon property to return Optional[Icon]
The Costume.icon computed field assumes that sideIconName is always present in the API response:

return Icon(side_icon_ui_path=self.data["sideIconName"], is_costume=True)

However, some costumes returned by the Enka API do not include the sideIconName field. This leads to:

KeyError when accessing the field directly
After switching to .get(...), a ValidationError because None is passed to Icon, which expects a string

This error is triggered implicitly when:

calling print(response)
calling model_dump()
or any operation that evaluates computed field

response = await client.fetch_showcase(<UID>)
print(response)

Results in:

KeyError: 'sideIconName'

so i fixed it with treating it as optional
such that it prevents those issues